### ISSUE TITLE
Cannot find module node_modules/react-native/Libraries/Core/InitializeCore

### ISSUE THREAD

**Issue by francois-pasquier** [facebook/metro#1263]
On Android, after migrating from react native 0.72 to 0.74, I am encountering this error:

`Cannot find module /**/ node_modules/react-native/Libraries/Core/InitializeCore`

Any insight on this one?

EDIT: nvm, it was on my end, I had a `react-native.config.js` badly configured, I got rid of it and the module resolution was alright afterward!
